### PR TITLE
Add authentication via Google API.

### PR DESCRIPTION
**Pull request by philiplambok**
Add authentication via Google API #1

### CODE REVIEW

**Comment by mfirmanakbar** [comment]
bro pindah yok ke bitbucket wkwk

**Comment by philiplambok** [comment]
> bro pindah yok ke bitbucket wkwk

Why man? Kata mang @hendrixsilaen di Github itu biar profil kita ijo2 wkwkw

**Comment by philiplambok** [comment]
ping @hendrixsilaen

**Comment by hendrixsilaen** [comment]
asiiikk,, udah di merge... 😂

**Comment by philiplambok** [comment]
Yeayy wkwkw

**Comment by mfirmanakbar** [comment]
mantap pagi2 🤣

**Pull request merged**
